// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iavfslzyiwdlrtvktnsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhdmZzbHp5aXdkbHJ0dmt0bnNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MjMwMDQsImV4cCI6MjA2OTE5OTAwNH0.i47RgeHYpLDnsDbQZn2xqoN7aaPVY8LGNa_WAzbAKEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});